# Usar uma imagem base do Nginx
FROM nginx:latest

# Criar o diretório snippets
RUN mkdir -p /etc/nginx/snippets

# Copiar a configuração do site para o diretório correto
COPY site.conf /etc/nginx/conf.d/default.conf

# Copiar o arquivo fastcgi-php.conf para o diretório snippets
COPY fastcgi-php.conf /etc/nginx/snippets/fastcgi-php.conf
