version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-gestao:1.0.0
    container_name: nginx-gestao
    volumes:
      - ./public:/var/www/public
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.http.routers.erp_gestao.entrypoints=websecure
      - traefik.http.routers.erp_gestao.rule=Host(`erp.agilytech.com`)
      - traefik.http.routers.erp_gestao.tls.certresolver=letsencryptresolver
      - traefik.http.services.erp_gestao.loadbalancer.server.port=80
    restart: unless-stopped
    networks:
      - gestao

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-gestao:1.0.0
    container_name: php-gestao
    volumes:
      - ./:/var/www:rw,delegated
      - ./logs:/var/www/writable/logs:rw,delegated
    environment:
      - CI_ENVIRONMENT=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gestao_database
      - DB_USERNAME=root
      - DB_PASSWORD=Jv410551
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - gestao

  mysql:
    image: mysql:5.7
    container_name: mysql-gestao
    environment:
      MYSQL_ROOT_PASSWORD: Jv410551
      MYSQL_DATABASE: gestao_database
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - gestao

volumes:
  mysql_data:

networks:
  gestao:
    external: true